---
- hosts: localhost
  tasks:
    - name: set facts
      set_fact:
        user: vinayvikas
        project: javawar
    - name: pushing to github
      commands: 'git push https://github.com/"{{ user }}"/"{{ project }}".git'
